### ISSUE TITLE
Smoke test checklist UI

### ISSUE THREAD

**Issue by Gromoff9999** [AndreySurzhan/ChecklistSLWebUi#45]
**Perform smok test UI on QA environmental:**
https://qachecklistsl-web.herokuapp.com/login

**Test run:**
https://docs.google.com/spreadsheets/d/1vaiHCMa5tMVdQdeVLPb624UmrlySEgKyNg23FCcADw0/edit#gid=0

**Comment by Gromoff9999** [comment]
**Test run was pass.**

 **_Environment:_**
1. https://qachecklistsl-web.herokuapp.com/login
2. https://checklistsl-web.herokuapp.com/login

**_Result_**: 
1. Bug: https://github.com/AndreySurzhan/ChecklistSLApi/issues/29
2. Bug: https://github.com/AndreySurzhan/ChecklistSLApi/issues/30  

**_Test run:_**
https://docs.google.com/spreadsheets/d/1vaiHCMa5tMVdQdeVLPb624UmrlySEgKyNg23FCcADw0/edit#gid=0

Ticket can be closed

**Comment by Sh1karno** [comment]
**Task verivied**
